apiVersion: v1
kind: Service
metadata:
  name: vprodb #based on the application.properties file vprodb is the name of the service.
# jdbc.url=jdbc:mysql://vprodb:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
spec:
  selector:
    app: vprodb # the label of the pod to be attached to
  ports:
  - port: 3306
    targetPort: vprodb-port #we could write 3306 or connect to the port number name of the db deployment, which is recommended.
    protocol: TCP
  type: ClusterIP #private IP to be used internally
