apiVersion: v1
kind: Service
metadata:
  name: vprocache01 #same as in application.properties memcached.active.host
spec:
  selector:
    app: vpromc # the label of the pod to be attached to
  ports:
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  type: ClusterIP #private IP to be used internally
