apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vproapp # the label of the pod to be attached to
  ports:
  - port: 80
    targetPort: vproapp-port #to 8080
    protocol: TCP
  type: LoadBalancer #pubic IP, load balancer
